name: Selenium Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable fonts-liberation libxss1 libappindicator1 libindicator7 xdg-utils libnss3 libgconf-2-4 libxss1 libxtst6 libegl1

      - name: Run Tests
        run: mvn test
